const path = require('path');
require('dotenv').config({ path: path.join(__dirname, '.env') });
console.log("DEBUG ENV CHECK (FORCED PATH):", process.env.DEEPSEEK_API_KEY ? "EXISTS" : "MISSING");
const AiGenerator = require('./services/AiGenerator');

async function testIntegration() {
    console.log("--- PROJECT INTEGRATION TEST START ---");
    console.log("Theme: Test Dragon");
    
    try {
        // This will trigger the flow: Gemini (fail) -> DeepSeek (attempt)
        const result = await AiGenerator.generateBossPrototype("Neon Dragon", "[]", "");
        
        console.log("\n--- TEST SUCCESS ---");
        console.log("Boss Name:", result.name);
        console.log("Generated By AI:", result.generatedByAI);
    } catch (err) {
        console.log("\n--- TEST LOGS FROM GENERATOR ---");
        if (err.logs) {
            err.logs.forEach(l => console.log(l));
        }
        
        console.error("\n--- INTEGRATION ERROR ---");
        console.error(err.message);
        
        if (err.message.includes("Insufficient Balance")) {
            console.log("\n💡 ANALİZ: Kod entegrasyonu BAŞARILI. DeepSeek ile bağlantı kuruldu, kodlar çalıştı.");
            console.log("Ancak DeepSeek hesabında bakiye olmadığı için API veriyi reddetti.");
        }
    }
}

testIntegration();
